# Generated by Django 5.2.10 on 2026-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0003_meditationhaptic'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meditation',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meditation',
            name='script',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meditation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
